In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import pairwise_distances

In [2]:
pwd

u'/Users/michaelhood/Documents/projects/project/code'

In [3]:
cd ../data/san_fran/

/Users/michaelhood/Documents/projects/project/data/san_fran


In [4]:
df_sf = pd.read_csv('normalized_sf.csv', index_col=0)
df_sf = df_sf.reset_index(drop=True)
df_sea = pd.read_csv('normalized_sea.csv', index_col=0)
df_sea = df_sea.reset_index(drop=True)

In [5]:
df_sf.head()

bathrooms  bedrooms  finishedsqft  numrooms  yearbuilt     price  \
0   0.142857       0.3      0.168207  0.388889   0.241379  0.046068   
1   0.142857       0.1      0.059964  0.111111   0.703448  0.019520   
2   0.000000       0.2      0.136107  0.277778   0.206897  0.056644   
3   0.000000       0.1      0.046739  0.222222   0.206897  0.031942   
4   0.285714       0.4      0.232409  0.555556   0.027586  0.163260   

   trans_score  walkscore_score  
0         0.44         0.686869  
1         0.29         0.313131  
2         0.85         0.979798  
3         0.82         0.969697  
4         0.87         0.989899

In [6]:
cd ../../code

/Users/michaelhood/Documents/projects/project/code


In [7]:
sim_mat = pairwise_distances(df_sf, df_sea, metric='euclidean', n_jobs=-1) # need to comp a new distance metric

In [8]:
# sf is rows and sea is cols

def get_most_similar(sim_mat, ref_listing, num_matches):
    '''
    Input: similarity matrix with first arg of parwise distances as rows and
           second arg of pairwise distances as columns, the integer index of the 
           listing you want to compare other listings to, int for the num of listings
           to return.
           
    Output: an numpy array with the indices of the listings in the other city that
            are most similar to the ref_listing.
    '''
    
    return np.argsort(sim_mat[ref_listing])[-(num_matches):]

In [31]:
euc = get_most_similar(pairwise_distances(df_sf, df_sea, metric='euclidean', n_jobs=-1), 0, 5)
cos = get_most_similar(pairwise_distances(df_sf, df_sea, metric='cosine', n_jobs=-1), 0, 5)
dist = get_most_similar(pairwise_distances(df_sf, df_sea, metric=distance, n_jobs=-1), 0, 5)
wdist = get_most_similar(pairwise_distances(df_sf, df_sea, metric=walker_distance, n_jobs=-1), 0, 5)

In [32]:
print euc
print cos
print dist
print wdist

[145 141 149  44  85]
[63 33 95 96 85]
[ 85  28 123  44 145]
[ 51  85  52  47 141]


In [30]:
from space_lover import distance
from walker_distance import walker_distance

In [13]:

v1 = df_sf.ix[0].values
v2 = df_sea.ix[0].values

In [14]:
distance(v1, v2)

0.452396583752618

In [20]:
df_sf.head()

bathrooms  bedrooms  finishedsqft  numrooms  yearbuilt     price  \
0   0.142857       0.3      0.168207  0.388889   0.241379  0.046068   
1   0.142857       0.1      0.059964  0.111111   0.703448  0.019520   
2   0.000000       0.2      0.136107  0.277778   0.206897  0.056644   
3   0.000000       0.1      0.046739  0.222222   0.206897  0.031942   
4   0.285714       0.4      0.232409  0.555556   0.027586  0.163260   

   trans_score  walkscore_score  
0         0.44         0.686869  
1         0.29         0.313131  
2         0.85         0.979798  
3         0.82         0.969697  
4         0.87         0.989899